using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FrameworksAndDrivers.DataAccess.DbEntities
{
    [Table("COND_LOC")]
    public class CondLoc
    {
        [Key] 
        public long SEQID { get; set; }
        public long LOCID { get; set; }
        public long? TESTID { get; set; }
        public long? TESTS { get; set; }
        public double? PERIOD { get; set; }
        public bool? PLANOK { get; set; }
        public DateTime? TESTSTART { get; set; }
        public DateTime? TSN { get; set; }
        public DateTime? TSA { get; set; }
        public long? STATID { get; set; }
        public long? METHID { get; set; }
        public double? MDNOM { get; set; }
        public double? MDMIN { get; set; }
        public double? MDMAX { get; set; }
        public double? MDLO { get; set; }
        public double? MDHI { get; set; }
        public long? DEGREE { get; set; }
        public double? MF { get; set; }
        public long? TOOLID { get; set; }
        public DateTime? LAST_CTL { get; set; }
        public long? CTL_ID { get; set; }
        public DateTime? NEXT_CTL { get; set; }
        public long? CTL_RES { get; set; }
        public long? NTRANS { get; set; }
        public double? LOSEMIN { get; set; }
        public double? LOSEMAX { get; set; }
        public double? OEGX { get; set; }
        public double? UEGX { get; set; }
        public double? OEGS { get; set; }
        public double? OEGR { get; set; }
        public long? USE_OEGX { get; set; }
        public long? USE_UEGX { get; set; }
        public long? USE_OEGS { get; set; }
        public long? USE_OEGR { get; set; }
        public long TYPEID { get; set; }
        public double? OEGN { get; set; }
        public double? UEGN { get; set; }
        public double? DELTAN { get; set; }
        public double? DELTAX { get; set; }
        public long? USE_OEGN { get; set; }
        public long? USE_UEGN { get; set; }
        public long? USE_DELTAN { get; set; }
        public long? USE_DELTAX { get; set; }
        public long? FLAGS { get; set; }
        public double? F1 { get; set; }
        public double? F2 { get; set; }
        public double? F3 { get; set; }
        public double? F4 { get; set; }
        public double? F5 { get; set; }
        public long? I1 { get; set; }
        public long? I2 { get; set; }
        public long? I3 { get; set; }
        public long? I4 { get; set; }
        public long? IPMOK { get; set; }
        public String SAFO_NR { get; set; }
        public DateTime? LASTLPFU { get; set; }
        public DateTime? LASTVPFU { get; set; }
        public bool RECLAMATION { get; set; }
        public long? BEARB { get; set; }
        public long? BERICHT { get; set; }
        public double? FNOMMT { get; set; }
        public double? FMSMT { get; set; }
        public long? FDEGMT { get; set; }
        public double? SCHSTARTMEA { get; set; }
        public double? SCHWIMIN { get; set; }
        public double? SCHWIMAX { get; set; }
        public double? SCHNOM { get; set; }
        public double? SCHUG { get; set; }
        public double? SCHOG { get; set; }
        public double? SCHFW { get; set; }
        public double? MIDDLE { get; set; }
        public double? SIGMA { get; set; }
        public double? LIMITORIGIN { get; set; }
        public long? IFREQUENCY { get; set; }
        public long? IDYNSTEP { get; set; }
        public double? FLASTDYN { get; set; }
        public bool USEMANFREQU { get; set; }
        public double? MINLOAD { get; set; }
        public bool USECARCOUNT { get; set; }
        public long ICARCOUNTER { get; set; }
        public long? REHITDEG { get; set; }
        public double? FTORQUEALARM { get; set; }
        public double? FANGLEALARM { get; set; }
        public double? F6 { get; set; }
        public double? F7 { get; set; }
        public double? F8 { get; set; }
        public double? F9 { get; set; }
        public long? SB_RESOLUTION { get; set; }
        public double? STOP_ANGLE { get; set; }
        public double? STOP_ANGLE_SB { get; set; }
        public long? LLIMID { get; set; }
        public DateTime? LAST_PV { get; set; }
        public double? AC_CHANGESCREW { get; set; }
        public long? AC_RATCHETTIME { get; set; }
        public long? AC_MAXCOHERENTNOK { get; set; }
        public double? AC_BAANGLETHRESHOLD { get; set; }
        public double? AC_RESANGLETHRESHOLD { get; set; }
        public double? AC_CYCLESTART { get; set; }
        public double? AC_STARTFINALANGLE { get; set; }
        public DateTime? MISS_CTL { get; set; }
        public bool USE_FREQ { get; set; }
        public long? NEXTSHIFT { get; set; }
        public DateTime? ENDOFLASTTESTPERIOD { get; set; }
        public long? ENDOFLASTTESTPERIODSHIFT { get; set; }
        public long? TESTLEVELSETID { get; set; }
        public int TESTLEVELNUMBER { get; set; }
        public bool ALIVE { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<CondLocTech> CondLocTechs { get; set; }
    }

    [Table("CONDLOCCHANGES")]
    public class CondLocChanges
    {
        [Key] 
        public long GLOBALHISTORYID { get; set; }
        public long CONDLOCID { get; set; }
        public long USERID { get; set; }
        public String ACTION { get; set; }
        public String USERCOMMENT { get; set; }
        public long LOCIDNEW { get; set; }
        public long LOCIDOLD { get; set; }
        public long? TESTIDNEW { get; set; }
        public long? TESTIDOLD { get; set; }
        public long? TESTSNEW { get; set; }
        public long? TESTSOLD { get; set; }
        public double? PERIODNEW { get; set; }
        public double? PERIODOLD { get; set; }
        public bool? PLANOKNEW { get; set; }
        public bool? PLANOKOLD { get; set; }
        public DateTime? TESTSTARTNEW { get; set; }
        public DateTime? TESTSTARTOLD { get; set; }
        public long? STATIDNEW { get; set; }
        public long? STATIDOLD { get; set; }
        public long? METHIDNEW { get; set; }
        public long? METHIDOLD { get; set; }
        public double? MDNOMNEW { get; set; }
        public double? MDNOMOLD { get; set; }
        public double? MDMINNEW { get; set; }
        public double? MDMINOLD { get; set; }
        public double? MDMAXNEW { get; set; }
        public double? MDMAXOLD { get; set; }
        public double? MDLONEW { get; set; }
        public double? MDLOOLD { get; set; }
        public double? MDHINEW { get; set; }
        public double? MDHIOLD { get; set; }
        public long? DEGREENEW { get; set; }
        public long? DEGREEOLD { get; set; }
        public double? MFNEW { get; set; }
        public double? MFOLD { get; set; }
        public long? TOOLIDNEW { get; set; }
        public long? TOOLIDOLD { get; set; }
        public DateTime? LAST_CTLNEW { get; set; }
        public DateTime? LAST_CTLOLD { get; set; }
        public long? CTL_IDNEW { get; set; }
        public long? CTL_IDOLD { get; set; }
        public DateTime? NEXT_CTLNEW { get; set; }
        public DateTime? NEXT_CTLOLD { get; set; }
        public long? CTL_RESNEW { get; set; }
        public long? CTL_RESOLD { get; set; }
        public long? NTRANSNEW { get; set; }
        public long? NTRANSOLD { get; set; }
        public double? LOSEMINNEW { get; set; }
        public double? LOSEMINOLD { get; set; }
        public double? LOSEMAXNEW { get; set; }
        public double? LOSEMAXOLD { get; set; }
        public double? OEGXNEW { get; set; }
        public double? OEGXOLD { get; set; }
        public double? UEGXNEW { get; set; }
        public double? UEGXOLD { get; set; }
        public double? OEGSNEW { get; set; }
        public double? OEGSOLD { get; set; }
        public double? OEGRNEW { get; set; }
        public double? OEGROLD { get; set; }
        public long? USE_OEGXNEW { get; set; }
        public long? USE_OEGXOLD { get; set; }
        public long? USE_UEGXNEW { get; set; }
        public long? USE_UEGXOLD { get; set; }
        public long? USE_OEGSNEW { get; set; }
        public long? USE_OEGSOLD { get; set; }
        public long? USE_OEGRNEW { get; set; }
        public long? USE_OEGROLD { get; set; }
        public int TYPEIDNEW { get; set; }
        public int TYPEIDOLD { get; set; }
        public double? OEGNNEW { get; set; }
        public double? OEGNOLD { get; set; }
        public double? UEGNNEW { get; set; }
        public double? UEGNOLD { get; set; }
        public double? DELTANNEW { get; set; }
        public double? DELTANOLD { get; set; }
        public double? DELTAXNEW { get; set; }
        public double? DELTAXOLD { get; set; }
        public long? USE_OEGNNEW { get; set; }
        public long? USE_OEGNOLD { get; set; }
        public long? USE_UEGNNEW { get; set; }
        public long? USE_UEGNOLD { get; set; }
        public long? USE_DELTANNEW { get; set; }
        public long? USE_DELTANOLD { get; set; }
        public long? USE_DELTAXNEW { get; set; }
        public long? USE_DELTAXOLD { get; set; }
        public long? FLAGSNEW { get; set; }
        public long? FLAGSOLD { get; set; }
        public double? F1NEW { get; set; }
        public double? F1OLD { get; set; }
        public double? F2NEW { get; set; }
        public double? F2OLD { get; set; }
        public double? F3NEW { get; set; }
        public double? F3OLD { get; set; }
        public double? F4NEW { get; set; }
        public double? F4OLD { get; set; }
        public double? F5NEW { get; set; }
        public double? F5OLD { get; set; }
        public long? I1NEW { get; set; }
        public long? I1OLD { get; set; }
        public long? I2NEW { get; set; }
        public long? I2OLD { get; set; }
        public long? I3NEW { get; set; }
        public long? I3OLD { get; set; }
        public long? I4NEW { get; set; }
        public long? I4OLD { get; set; }
        public long? IPMOKNEW { get; set; }
        public long? IPMOKOLD { get; set; }
        public String SAFO_NRNEW { get; set; }
        public String SAFO_NROLD { get; set; }
        public DateTime? LASTLPFUNEW { get; set; }
        public DateTime? LASTLPFUOLD { get; set; }
        public DateTime? LASTVPFUNEW { get; set; }
        public DateTime? LASTVPFUOLD { get; set; }
        public bool RECLAMATIONNEW { get; set; }
        public bool RECLAMATIONOLD { get; set; }
        public long? BEARBNEW { get; set; }
        public long? BEARBOLD { get; set; }
        public long? BERICHTNEW { get; set; }
        public long? BERICHTOLD { get; set; }
        public double? FNOMMTNEW { get; set; }
        public double? FNOMMTOLD { get; set; }
        public double? FMSMTNEW { get; set; }
        public double? FMSMTOLD { get; set; }
        public long? FDEGMTNEW { get; set; }
        public long? FDEGMTOLD { get; set; }
        public double? SCHSTARTMEANEW { get; set; }
        public double? SCHSTARTMEAOLD { get; set; }
        public double? SCHWIMINNEW { get; set; }
        public double? SCHWIMINOLD { get; set; }
        public double? SCHWIMAXNEW { get; set; }
        public double? SCHWIMAXOLD { get; set; }
        public double? SCHNOMNEW { get; set; }
        public double? SCHNOMOLD { get; set; }
        public double? SCHUGNEW { get; set; }
        public double? SCHUGOLD { get; set; }
        public double? SCHOGNEW { get; set; }
        public double? SCHOGOLD { get; set; }
        public double? SCHFWNEW { get; set; }
        public double? SCHFWOLD { get; set; }
        public double? MIDDLENEW { get; set; }
        public double? MIDDLEOLD { get; set; }
        public double? SIGMANEW { get; set; }
        public double? SIGMAOLD { get; set; }
        public double? LIMITORIGINNEW { get; set; }
        public double? LIMITORIGINOLD { get; set; }
        public long? IFREQUENCYNEW { get; set; }
        public long? IFREQUENCYOLD { get; set; }
        public long? IDYNSTEPNEW { get; set; }
        public long? IDYNSTEPOLD { get; set; }
        public double? FLASTDYNNEW { get; set; }
        public double? FLASTDYNOLD { get; set; }
        public bool USEMANFREQUNEW { get; set; }
        public bool USEMANFREQUOLD { get; set; }
        public double? MINLOADNEW { get; set; }
        public double? MINLOADOLD { get; set; }
        public bool USECARCOUNTNEW { get; set; }
        public bool USECARCOUNTOLD { get; set; }
        public long ICARCOUNTERNEW { get; set; }
        public long ICARCOUNTEROLD { get; set; }
        public long? REHITDEGNEW { get; set; }
        public long? REHITDEGOLD { get; set; }
        public double? FTORQUEALARMNEW { get; set; }
        public double? FTORQUEALARMOLD { get; set; }
        public double? FANGLEALARMNEW { get; set; }
        public double? FANGLEALARMOLD { get; set; }
        public double? F6NEW { get; set; }
        public double? F6OLD { get; set; }
        public double? F7NEW { get; set; }
        public double? F7OLD { get; set; }
        public double? F8NEW { get; set; }
        public double? F8OLD { get; set; }
        public double? F9NEW { get; set; }
        public double? F9OLD { get; set; }
        public long? SB_RESOLUTIONNEW { get; set; }
        public long? SB_RESOLUTIONOLD { get; set; }
        public double? STOP_ANGLENEW { get; set; }
        public double? STOP_ANGLEOLD { get; set; }
        public double? STOP_ANGLE_SBNEW { get; set; }
        public double? STOP_ANGLE_SBOLD { get; set; }
        public long? LLIMIDNEW { get; set; }
        public long? LLIMIDOLD { get; set; }
        public DateTime? LAST_PVNEW { get; set; }
        public DateTime? LAST_PVOLD { get; set; }
        public double? AC_CHANGESCREWNEW { get; set; }
        public double? AC_CHANGESCREWOLD { get; set; }
        public long? AC_RATCHETTIMENEW { get; set; }
        public long? AC_RATCHETTIMEOLD { get; set; }
        public long? AC_MAXCOHERENTNOKNEW { get; set; }
        public long? AC_MAXCOHERENTNOKOLD { get; set; }
        public double? AC_BAANGLETHRESHOLDNEW { get; set; }
        public double? AC_BAANGLETHRESHOLDOLD { get; set; }
        public double? AC_RESANGLETHRESHOLDNEW { get; set; }
        public double? AC_RESANGLETHRESHOLDOLD { get; set; }
        public double? AC_CYCLESTARTNEW { get; set; }
        public double? AC_CYCLESTARTOLD { get; set; }
        public double? AC_STARTFINALANGLENEW { get; set; }
        public double? AC_STARTFINALANGLEOLD { get; set; }
        public DateTime? MISS_CTLNEW { get; set; }
        public DateTime? MISS_CTLOLD { get; set; }
        public bool USE_FREQNEW { get; set; }
        public bool USE_FREQOLD { get; set; }
        public long NEXTSHIFTNEW { get; set; }
        public long NEXTSHIFTOLD { get; set; }
        public DateTime? ENDOFLASTTESTPERIODNEW { get; set; }
        public DateTime? ENDOFLASTTESTPERIODOLD { get; set; }
        public long ENDOFLASTTESTPERIODSHIFTNEW { get; set; }
        public long ENDOFLASTTESTPERIODSHIFTOLD { get; set; }
        public long? TESTLEVELSETIDNEW { get; set; }
        public long? TESTLEVELSETIDOLD { get; set; }
        public int? TESTLEVELNUMBERNEW { get; set; }
        public int? TESTLEVELNUMBEROLD { get; set; }
        public bool? ALIVENEW { get; set; }
        public bool? ALIVEOLD { get; set; }
    }
}